- README.md
I discovered this nicely made site that I feel could add value to this list.
Feel free to move it to a different category. I had a hard time deciding where it should go.
> Add switching.social

- README.md
> Replace "Probe" with "OONI Probe"

- README.md
PRISM Break is a software recommendation site that helps people to gain control over their privacy.
> Add PRISM Break to Privacy category

- README.md
I think this qualifies as it's open source, non-commercial, and free of any distractions.
> Add MindBell

- README.md
It moved from GitHub to GitLab
> Update URL for "Mindfulness at the Computer"

- pull_request_template.md
Added PR template for new submissions
> Added PR template for new submissions 

- README.md
Updating the 1 line description of the entry for my project which was already added by Arnold earlier.
> Update cloud firewall entry 1 line description

- README.md
Helps protect oneself and people from tracking elements added to URLs. It uses 130 rules to remove  tracking fields added by sites to address bar URLs. In general, these tracking fields are not required for functionality and hence web sites/pages are expected to still load the same way.
[Gitlab](https://gitlab.com/KevinRoebert/ClearUrls/blob/master/README.md) License QaPL v0.2 created by Kevin R and other contributors. 
[Download/install page](https://addons.mozilla.org/en-US/firefox/addon/clearurls/)
I did not create or contribute (yet) to this project. I wish to submit Kevin R's project to Humane Tech list.
Yes : how does this project differ from the existing one? The author says this in their Mozilla store listing : 
> The main differences between this and similar add-ons are they have …
> Include ClearURLs browser extension to HT

- README.md
Pi-hole
Allows users to safeguard their privacy and attention by blocking ads and trackers.
https://github.com/pi-hole/pi-hole
EUROPEAN UNION PUBLIC LICENCE v. 1.2
Yes, but this is the only one I have seen positioned as a general purpose blocker for an entire local network. Also the project is mature and has some prominence (14k GitHub stars, and a [popular Reddit community](https://www.reddit.com/r/pihole))
I have no involvement with the Pi-hole project. I just discovered it but think it belongs here.
> Add Pi-hole (Tracking)

- README.md
The A11Y Project
We have many resources on how to make websites more accessible to everyone, and use a community-driven focus to create these resources.
https://github.com/a11yproject/a11yproject.com
Yes, there are other sites that also host web accessibility information, but ours allows anyone to submit articles that are then reviewed by the contributing team. 
The A11Y Project is guided by three principles:
- Digestible. Articles on accessibility tend to be in-depth, sometimes to their detriment. We prefer to feature short, digestible pieces of content.
- Up-to-date. We strive to keep information current with the latest standards and the realities of real-world technology support.
- Forgiving. People make mistakes and web accessibility can be difficult, so we seek to be encouraging.
> Add The A11Y Project

- README.md
Lets users track how they spend their time, helping them to spend it better.
- GitHub: https://github.com/ActivityWatch/activitywatch
- License: MPL2.0
Yes, there is a summary of them and motivations for why they aren't enough in the README.
> Added ActivityWatch

- README.md
EteSync
It secures (and keeps private) your contacts, calendar and tasks.
No, only one out there. Has been around for several years now. It's on many similar lists including privacytools and prism-break. 
Everything is open source. Clients and server and development is very active.
> Privacy section: Add EteSync 

- README.md
Bibliogram
Bibliogram respects its users and helps them move away from Instagram, a disrespectful service. It is similar to Invidious and Nitter, which are already on the list.
https://github.com/cloudrac3r/bibliogram
I couldn't find anything like Bibliogram, which is why I felt it was important to create it. Invidious and Nitter already exist for YouTube and Twitter, but there was nothing for Instagram, which is also a popular website.
> Add Bibliogram

- README.md
InstaGrabber
* Allows searching profiles, hashtags, and locations, without logging into Instagram
* Opening the app, you're greeted with your own profile (or an empty page), not your feed
* It is much easier to see your liked posts (it's a big pink button in your own profile vs. having to navigate through various settings in the official Instagram app)
* Likewise, the button to like posts aren't that obvious: You must click into the post and press the button (no simple double-tap or a convenient button). This (and above) allows users to be conscious of their likes.
* Allows anonymous viewing of stories, protects privacy
Overall, it gives you a responsible alternative over the official Instagram app, with similar features. Also, read …
> Add InstaGrabber

- README.md
Yes : how does my project differ from the existing one (also include how it differs in terms of humane ethical reasons?  
No : Try to explain why and the motivations, goals, and purpose if you can, so that we can understand your project better and it will help us speak about your work.
> Update README.md - typo fix in Community section

- README.md
Hey @aschrijver
just a fix of a broken link in the list.
Cheers!
> Fixing link to hack-the-media

- README.md
The Hippocratic License, Version 2.1
As developers invested in humane technology, we are all too aware of the potential for code that we write to be used for unethical purposes - a fact that we must bear in mind with every project that we build.  Yet when we license our projects, we are often forced to choose between granting rights to our users, and keeping rights from those who might use our software for evil.
As a consequence, we find far too often that well-meaning code released with the rights of our users in mind ends up being used to deprive others of their rights, as [is the case with ICE](https://icebreaker.dev/), and an unfortunately high other number of cases.
The Hippocratic license is the flagship [Ethical Source License](https://ethicalsource.dev/licenses/), a class of …
> Add the Hippocratic License

- README.md
- logo/codeberg.svg
This adds Codeberg icon to related entries - projects hosted on Codeberg.
Codeberg SVG icon is taken from https://github.com/edent/SuperTinyIcons
Yes : how does my project differ from the existing one (also include how it differs in terms of humane ethical reasons?  
No : Try to explain why and the motivations, goals, and purpose if you can, so that we can understand your project better and it will help us speak about your work.
> add Codeberg logo to projects hosted on Codeberg

- README.md
Yes:
- Libreddit is themed around Reddit's redesign whereas Teddit appears to stick much closer to Reddit's old design. This may suit some users better as design is always subjective.
- Libreddit is written in Rust for speed and memory safety. It uses Actix Web, which was [benchmarked as the fastest web server for single queries](https://www.techempower.com/benchmarks/#hw=ph&test=db).
- Unlike Teddit (at the time of writing this), Libreddit does not require a Reddit API key to host.
- Libreddit supports post and user flairs.
I've been using this list for a while and thought it would be a good submission to add Libreddit (Libre + Reddit = Libreddit), my private Reddit frontend, to Humane Tech.
> Add Libreddit

- README.md
Yes
1. This product allows any company to host its own data in a secure way.
2. Companies do not need to reinvent the wheel and create their own secure storage to store customer data.
I think this product is great for humanity. It will minimize the cases of customer data exposure in case companies using Databunker will get hacked.
> Databunker

- README.md
Deletion Day is [licensed under the GNU GPL v3](https://github.com/deletionday/site/blob/master/COPYING)
[**Deletion Day**](https://deletionday.com)
Deletion Day directly opposes the privacy and security overreaches perpetrated by today’s tech industry.
[…on Github](https://github.com/deletionday/site/)
I’ve found instances of one-off data deletion events, for instance:
- [The International Association of Privacy Professionals Deletion Day (2018)](https://iapp.org/news/a/data-deletion-day/)
- [Montgomery Public Schools’ “Data Deletion Week”](https://www.theguardian.com/education/2019/dec/05/schools-monitor-students-online-activity)
…but as far as I know, this is the first effort to form a recurring awareness campaign around this issue.
Excerpt from …
> Add Deletion Day

- README.md
Yes : how does my project differ from the existing one (also include how it differs in terms of humane ethical reasons?  
No : Try to explain why and the motivations, goals, and purpose if you can, so that we can understand your project better and it will help us speak about your work.
> awesome-decentralized: use popular repo

- README.md
A new list, **awesome-sustainable-vps**.
We need more humane, slow, sustainable VPS providers. The discussion with Humanetech started in this toot: https://mastodon.social/@humanetech/106866898304501053
https://codeberg.org/jonatasbaldin/awesome-sustainable-vps
> Add awesome-sustanaible-vps

- README.md
Piped
You escape Google's tracking.
Yes - Invidious : Piped was created to fix the performance and architectural problems that were existent in Invidious, and to add features rapidly.
> Add Piped.

- README.md
https://wikitruth.co/ didn't resolve for me, and their GitHub repo points to https://wikitruth.net/.
> Fix WikiTruth link

- README.md
A Chrome extension that disables Autocomplete and other distracting elements on Google's pages.
Mindful Google™
It helps with mindfullness when using the Google Search Engine. It disables Autocomplete and other distracting elements on Google's pages.
[Mindful-Google™](https://github.com/tunjos/Mindful-Google)
No: No extension so far helps to disable autocomplete on Google. This is a forced feature by Google. Some search engines like DuckDuckGo, Bing, etc. provide the possibility to completely disable autocomplete. Others like Google don't.  
Read more here...https://tunjos.co/blog/autocomplete-search-engine-can-be-evil/
> Add Mindful Google™

- README.md
Yes : The closest, **still-active** project for community subtitling/captioning is [Amara](https://amara.org/en/). Formerly open-source, [Amara went closed source](https://news.slashdot.org/story/20/01/18/1753246/another-project-goes-private-amara-stops-being-developed-as-open-source) last year. Amara is also limited to YouTube, and partners such as [TedX](https://www.youtube.com/watch?v=1wBZupNSmR0). Conversely, Nekocap is being developed as an open-source, strictly non-profit, project not only targeting YouTube but newer video sites such as BiliBili. Additionally, Nekocap places an emphasis on stylisation and rendering formatted subtitles.
In 2020, YouTube [removed their community captions …
> Translation > Nekocap

- README.md
LibRedirect
A simple extension that redirects to alternative privacy-friendly frontends.
Yes : It's fork off Privacy-redirect. Its development had stopped. we are develop & adding some feature like instance list updator.
> Add LibRedirect

- README.md
LibMedium is a full AGPL alternate-frontend to Medium.com, that is privacy focused. Medium.com is an excellent source of information from interesting authors, which would benefit a lot of people if the service chose a different business model, that freely shares knowledge. LibMedium was created to reflect these values.
Yes, LibMedium is inspired by [Scribe](https://scribe.rip), which is mentioned in the project's README and is already listed here. The project is meant to co-exist with Scribe and was created to scratch an itch in a tech stack that is familiar to me.
Yes : how does my project differ from the existing one (also include how it differs in terms of humane ethical reasons)? 
Both projects are created with similar values. LibMedium differs …
> add LibMedium to social network section

- README.md
Firezone
It's a self-hosted and open-source alternative to some hosted VPN providers which may log your traffic.
https://github.com/firezone/firezone
There are similar projects, but most are not actively maintained anymore (like [subspace](https://github.com/subspacecloud/subspace)). We're committed to open-source and also spend a significant amount of effort having good docs/guides (https://docs.firezone.dev/) so anyone can use it.
Thanks for maintaining this great list of projects!
> Add Firezone

- README.md
[Awesome Privacy](https://github.com/Lissy93/awesome-privacy/)
The aim of the repo is to provide a starting point to help users escape big tech. It's community driven, and I've put steps in place to keep everything as transparent as possible.
Yes! There are several other really great resources that also list privacy-respecting software. The biggest of those is probably [Privacy-Tools](https://www.privacytools.io/), [Privacy-Guides](https://www.privacyguides.org/), and [this](https://github.com/KevinColemanInc/awesome-privacy) repo. 
The main differentiating factor, is just that this list is (aiming to be) more comprehensive and more community driven. It includes more niche sections, like privacy-respecting budgeting tools, data eradication …
> Adds Awesome-Privacy under Related awesomeness
